# Generated by Django 4.1.13 on 2025-12-14 13:25

from django.db import migrations, models
import lf.models


class Migration(migrations.Migration):

    dependencies = [
        ('lf', '0009_notification_approver_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websiteuser',
            name='profile_image',
            field=models.ImageField(blank=True, default=lf.models.default_profile_image_path, null=True, upload_to='profile_images/'),
        ),
    ]
